### ISSUE TITLE
跟随所有文档步骤后，启动失败，请见截图

### ISSUE THREAD

**Issue by esirplayground** [ventoy/OpenWrtPlugin#2]
固件：官方19.07.7 Combined Squash Stable Version
硬件：J4125 全千兆工控机，无内置硬盘，U盘为Sandisk Extreme 32G
Plugin为最新版下载，存放在hd0  ventoy目录

![openwrt-1907 7-x86-64-squash-2](https://user-images.githubusercontent.com/50467624/122432996-cc3a0b00-cf63-11eb-8853-c99c02e662a8.png)
![Snipaste_2021-06-17_11-19-59](https://user-images.githubusercontent.com/50467624/122433146-f1c71480-cf63-11eb-8692-aeb26c969318.png)

**Comment by ventoy** [comment]
请做一下对比测试：
1、试试启动ext4的img文件
2、同一个U盘插在电脑上启动试试
3、使用rufus把img文件直接写到同一个U盘上启动试试
4、换个openwrt版本试试

**Comment by ventoy** [comment]
再做如下测试：
启动到 Ventoy 的主界面后，先按 `c` 进入命令行，执行 `vtbreak 0 1` 命令，回车执行完后，再按 `ESC` 返回主界面，
然后再选择img文件启动。
这样，正常在启动过程中会打印出一些绿色的调试信息，请截图发我看下。

**Comment by esirplayground** [comment]
> 
> 
> 请做一下对比测试：
> 1、试试启动ext4的img文件
> 2、同一个U盘插在电脑上启动试试
> 3、使用rufus把img文件直接写到同一个U盘上启动试试
> 4、换个openwrt版本试试

ventoy启动 ext4
![ventoyboot ext4](https://user-images.githubusercontent.com/50467624/122580038-89d80300-d023-11eb-850d-82e2842b6bf1.png)
rufus直写U盘-squash格式
![19 07 7 directboot squash](https://user-images.githubusercontent.com/50467624/122580114-9eb49680-d023-11eb-998c-feb0618d23ad.png)
rufus直写U盘-ext4格式
![19 07 7 directboot ext4](https://user-images.githubusercontent.com/50467624/122580159-a96f2b80-d023-11eb-9ce4-e338926f787a.png)

**Comment by esirplayground** [comment]
> 
> 
> 再做如下测试：
> 启动到 Ventoy 的主界面后，先按 `c` 进入命令行，执行 `vtbreak 0 1` 命令，回车执行完后，再按 `ESC` 返回主界面，
> 然后再选择img文件启动。
> 这样，正常在启动过程中会打印出一些绿色的调试信息，请截图发我看下。

![vtbreak](https://user-images.githubusercontent.com/50467624/122581421-07504300-d025-11eb-82b7-7970558e6736.png)
没有发现绿色信息 - ext4
![vtbreak ventoyboot ext4](https://user-images.githubusercontent.com/50467624/122583032-ce18d280-d026-11eb-9428-846d8764817b.png)
没有发现绿色信息 - squash
![vtbreak ventoyboot squash](https://user-images.githubusercontent.com/50467624/122583061-d83ad100-d026-11eb-834d-f5ae683e942e.png)

**Comment by ventoy** [comment]
Ventoy是用的最新版本吧？ 1.0.46

**Comment by esirplayground** [comment]
> 
> 
> Ventoy是用的最新版本吧？ 1.0.46

恩恩，那必须的

**Comment by ventoy** [comment]
前面我漏了一步。
vtbreak 0 1 还是正常执行，然后在下面这个位置不要按回车，按 `e` 进入菜单编辑界面：
![11](https://user-images.githubusercontent.com/59477474/122626844-21e6f280-d0df-11eb-97af-e83963efa27a.PNG)

然后按方向键移动光标，按 Backspace键删除如下部分的启动参数。
![22](https://user-images.githubusercontent.com/59477474/122626889-4216b180-d0df-11eb-83aa-69aea6fc5d34.PNG)

删除之后如下：
![33](https://user-images.githubusercontent.com/59477474/122626932-62df0700-d0df-11eb-885f-2022333159d0.PNG)


删除完之后，按 F10 或者 Ctrl + x 启动。看看有没有类似如下的信息：
![44](https://user-images.githubusercontent.com/59477474/122626919-5e1a5300-d0df-11eb-85d9-e9e51c7abd1e.PNG)

**Comment by esirplayground** [comment]
> 
> 
> 前面我漏了一步。
> vtbreak 0 1 还是正常执行，然后在下面这个位置不要按回车，按 `e` 进入菜单编辑界面：
> ![11](https://user-images.githubusercontent.com/59477474/122626844-21e6f280-d0df-11eb-97af-e83963efa27a.PNG)
> 
> 然后按方向键移动光标，按 Backspace键删除如下部分的启动参数。
> ![22](https://user-images.githubusercontent.com/59477474/122626889-4216b180-d0df-11eb-83aa-69aea6fc5d34.PNG)
> 
> 删除之后如下：
> ![33](https://user-images.githubusercontent.com/59477474/122626932-62df0700-d0df-11eb-885f-2022333159d0.PNG)
> 
> 删除完之后，按 F10 或者 Ctrl + x 启动。看看有没有类似如下的信息：
> ![44](https://user-images.githubusercontent.com/59477474/122626919-5e1a5300-d0df-11eb-85d9-e9e51c7abd1e.PNG)

grub 改掉以后提示 bad command line，继续引导，详细情况见贴图
![green](https://user-images.githubusercontent.com/50467624/122642903-c4e93d80-d0da-11eb-8336-92643e13473f.png)

**Comment by esirplayground** [comment]
以下截图是使用 **`LEAN LEDE`** 编译的固件相关截图, 内核已支持 `Device mapper`（但无ventoy插件不能继续引导）
硬件不变，固件更换为 `openwrt-buddha-v6[2021]-x86-64-generic-squashfs-combined.img.gz`

![device mapper](https://user-images.githubusercontent.com/50467624/122643398-94ef6980-d0dd-11eb-86aa-45f86d072101.png)
![device mapper-2](https://user-images.githubusercontent.com/50467624/122643400-96b92d00-d0dd-11eb-8d54-5fda97f00cca.png)
固件直刷U盘可以启动，准备脚本运行情况如下：
![buddha prepared](https://user-images.githubusercontent.com/50467624/122643687-4773fc00-d0df-11eb-916f-c7597409a803.png)

在Ventoy下启动详情见截图
![buddha grub](https://user-images.githubusercontent.com/50467624/122643672-23b0b600-d0df-11eb-8b21-d8fe7178edca.png)

![buddha ventoy boot](https://user-images.githubusercontent.com/50467624/122643697-5490eb00-d0df-11eb-89de-20b672af5cfd.png)

**Comment by esirplayground** [comment]
希望能和大佬在TG上交流，TG群地址：https://bit.ly/3ah4ygr

**Comment by ventoy** [comment]
把 前面的 `vtbreak 0 1` 改成 `vtbreak 03` （注意03之间没有空格）
然后再来一遍，那几个参数还是需要删除。
然后正常最后会进入一个命令行界面。
然后执行
```
/ventoy/tool/vtoydump  -f  /ventoy/ventoy_os_param  -v
```

**Comment by esirplayground** [comment]
> 
> 
> 把 前面的 `vtbreak 0 1` 改成 `vtbreak 03` （注意03之间没有空格）
> 然后再来一遍，那几个参数还是需要删除。
> 然后正常最后会进入一个命令行界面。
> 然后执行
> 
> ```
> /ventoy/tool/vtoydump  -f  /ventoy/ventoy_os_param  -v
> ```

换为 vtbreak 03 后引导，无法进入命令行界面
![vtbreak03 ventoyboot squash](https://user-images.githubusercontent.com/50467624/122649555-5ae19000-d0fc-11eb-9805-8a439447860d.png)

**Comment by ventoy** [comment]
console那几个参数删除了吗？另外再吧03换成01 和02分别试试 ---- 回复的原邮件 ***@***.***>发送日期2021年06月20日 00:48 ***@***.***> ***@***.******@***.***>主题Re: [ventoy/OpenWrtPlugin] 跟随所有文档步骤后，启动失败，请见截图 (#2)



把 前面的 vtbreak 0 1 改成 vtbreak 03 （注意03之间没有空格）

然后再来一遍，那几个参数还是需要删除。

然后正常最后会进入一个命令行界面。

然后执行

/ventoy/tool/vtoydump  -f  /ventoy/ventoy_os_param  -v





换为 vtbreak 03 后引导，无法进入命令行界面





—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ventoy/OpenWrtPlugin/issues/2#issuecomment-864434963",

"url": "https://github.com/ventoy/OpenWrtPlugin/issues/2#issuecomment-864434963",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by esirplayground** [comment]
> 
> console那几个参数删除了吗？另外再吧03换成01 和02分别试试 ---- 回复的原邮件 ***@***.***>发送日期2021年06月20日 00:48 ***@***.***> ***@***.******@***.***>主题Re: [ventoy/OpenWrtPlugin] 跟随所有文档步骤后，启动失败，请见截图 (#2) 把 前面的 vtbreak 0 1 改成 vtbreak 03 （注意03之间没有空格） 然后再来一遍，那几个参数还是需要删除。 然后正常最后会进入一个命令行界面。 然后执行 /ventoy/tool/vtoydump -f /ventoy/ventoy_os_param -v 换为 vtbreak 03 后引导，无法进入命令行界面 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#2 (comment)](https://github.com/ventoy/OpenWrtPlugin/issues/2#issuecomment-864434963)", "url": "[#2 (comment)](https://github.com/ventoy/OpenWrtPlugin/issues/2#issuecomment-864434963)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

用01进入命令行，但是没有vtoydump 文件，/ventoy/tool目录的文件列表如下：
如方便能否TG交流？
![ventoy ls](https://user-images.githubusercontent.com/50467624/122659195-5ee4d080-d143-11eb-80a8-1f879626525a.png)

**Comment by ventoy** [comment]
请使用这个CI版本，然后还是 `vtbreak 0 1` 再测试一次。
https://github.com/ventoy/Ventoy/actions/runs/953686240

我没有TG账号，你可以加官网的QQ群。

**Comment by esirplayground** [comment]
> 
> 
> 请使用这个CI版本，然后还是 `vtbreak 0 1` 再测试一次。
> https://github.com/ventoy/Ventoy/actions/runs/953686240
> 
> 我没有TG账号，你可以加官网的QQ群。

vtbreak 0 1，grub修改启动项后启动，反复在此界面跳
![newver vtbreak01](https://user-images.githubusercontent.com/50467624/122665244-1db8e480-d174-11eb-85c0-fcc8f1049533.png)

**Comment by ventoy** [comment]
请使用这个CI版本，先正常启动一次，看看能不能启动。如果不能，再和上面这样 `vtbreak 0 1` 看一下。
https://github.com/ventoy/Ventoy/actions/runs/954409264

**Comment by esirplayground** [comment]
> 
> 
> 请使用这个CI版本，先正常启动一次，看看能不能启动。如果不能，再和上面这样 `vtbreak 0 1` 看一下。
> https://github.com/ventoy/Ventoy/actions/runs/954409264

![1241 vtbreak01](https://user-images.githubusercontent.com/50467624/122675525-da786900-d1a7-11eb-8402-85735e74cbad.png)

**Comment by ventoy** [comment]
看来是找到设备了，最后起来了吗？ 按回车能进入系统了吗？

**Comment by ventoy** [comment]
哦，还有点问题，我还需要再修改下。

**Comment by ventoy** [comment]
请再试试这个CI版本
https://github.com/ventoy/Ventoy/actions/runs/954530442

**Comment by esirplayground** [comment]
> 
> 
> 请再试试这个CI版本
> https://github.com/ventoy/Ventoy/actions/runs/954530442

官方1907已经可以正常启动，进入openwrt后台，但是`Lean Lede` 还有问题，希望大佬一鼓作气搞定~
![Lean Code ventoy](https://user-images.githubusercontent.com/50467624/122924737-13dddf80-d334-11eb-9fde-52dd49b0d4fd.png)

**Comment by ventoy** [comment]
你把这个 `Lean Lede` 的img文件通过奶牛快传或者文叔叔给我共享一下。

**Comment by esirplayground** [comment]
> 
> 
> 你把这个 `Lean Lede` 的img文件通过奶牛快传或者文叔叔给我共享一下。

You have got one transfer，Click link: https://cowtransfer.com/s/9516a028b7eb4e or use code:502699 to receive your file on cowtransfer.com

MD5: ED4634D0945D65F63E4A5C302C8A1705
SHA1: 16E2C36587EDB5CDD5A78BF2C995193A7345C212
CRC32: FDEA8BF2

**Comment by ventoy** [comment]
请使用这个CI版本测试一下。
https://github.com/ventoy/Ventoy/actions/runs/970194639

正常持情况下，检测到img内部有dm-mod模块之后，就不会再强制要求必须有 ventoy_openwrt.xz文件了。

**Comment by esirplayground** [comment]
> 
> 
> 请使用这个CI版本测试一下。
> https://github.com/ventoy/Ventoy/actions/runs/970194639
> 
> 正常持情况下，检测到img内部有dm-mod模块之后，就不会再强制要求必须有 ventoy_openwrt.xz文件了。

非常感谢！请问，检测是挂载解包的时候呢，还是一开始就不用放这个xz的文件？

另外，这个版本的ventoy已经可以成功引导官方版和v6-buddha，但是 必须每次经过 “vtbreak 0 1” 和 “修改grub启动项”这两步，否则不能启动。

**Comment by ventoy** [comment]
一开始就不用放这个xz文件。

以官方版本为例：
1、你不执行 `vtbreak 0 1` 但是只 `修改 grub启动项`，是什么结果？
2、你不执行 `vtbreak 0 1`  也不 `修改 grub启动项`，是什么结果？
3、你直接把 img 文件通过Rufus烧到同一个U盘里面启动，是什么结果？

是不能启动，还是实际上已经启动，只是没有打印？ 最后机器有没有错误信息或者重启？

**Comment by ventoy** [comment]
最后再用这个 CI 版本试一次。
https://github.com/ventoy/Ventoy/actions/runs/978091729

**Comment by esirplayground** [comment]
> 
> 
> 最后再用这个 CI 版本试一次。
> https://github.com/ventoy/Ventoy/actions/runs/978091729

大佬厉害，已经可以完全不用输入任何命令，直接正常启动了
不过俺还有个问题，能不能让启动后的镜像可以读取到sda分区里里放置iso文件的内容？现在只能读取到sda2的内容，但是空间有限，不能放更多东西
![mnt lsblk](https://user-images.githubusercontent.com/50467624/123661526-9c5ff280-d802-11eb-8c0b-5be97837cc3f.png)

**Comment by ventoy** [comment]
这个无法读取。这个是Linux内核的限制，sda1里面的ISO文件被创建成了一个dm设备，这样sda1就不能再被挂载了。
这种情况下，你可以在安装Ventoy的时候，在U盘最后预留一部分空间，等安装完Ventoy以后，再利用这部分空间创建第3个分区，然后这个分区在启动之后就可以自由挂载使用了。参考：https://www.ventoy.net/cn/doc_disk_layout.html#reserve_space

**Comment by esirplayground** [comment]
> 
> 
> 这个无法读取。这个是Linux内核的限制，sda1里面的ISO文件被创建成了一个dm设备，这样sda1就不能再被挂载了。
> 这种情况下，你可以在安装Ventoy的时候，在U盘最后预留一部分空间，等安装完Ventoy以后，再利用这部分空间创建第3个分区，然后这个分区在启动之后就可以自由挂载使用了。参考：https://www.ventoy.net/cn/doc_disk_layout.html#reserve_space

谢谢，留出剩余空间非常好用
但是，启动逻辑还是会先检查插件文件是否存在，无论用不用的上还是要预备一个的
所以还是要放的，不加载还是检查不到内核是否已经支持dm，是不是？

![plugin](https://user-images.githubusercontent.com/50467624/123823402-270c2480-d8cb-11eb-9c01-f75f78d5802e.png)

**Comment by ventoy** [comment]
这个会检查img里面有没有 dm-mod.ko 文件，如果有的话就不会检查这个xz文件了，没有的话才会检查。
你上次传给我的那个img就不会检查了，因为里面包含了 dm-mod.ko文件。
如果不是把dm-mod.ko集成到img里面，而是dm模块直接编译到kernel内部了，这种情况下是检查不出来的，所以还是会检查。

**Comment by esirplayground** [comment]
> 
> 
> 这个会检查img里面有没有 dm-mod.ko 文件，如果有的话就不会检查这个xz文件了，没有的话才会检查。
> 你上次传给我的那个img就不会检查了，因为里面包含了 dm-mod.ko文件。
> 如果不是把dm-mod.ko集成到img里面，而是dm模块直接编译到kernel内部了，这种情况下是检查不出来的，所以还是会检查。

但是就如我前面发的截图一样，不放这个插件是会报错，提示找不到

**Comment by ventoy** [comment]
前面那个CI版本路径下：
`ventoy-windows.zip  md5: 8a620e85a2f4e4afea9f38ef43188a7b`
里面有个 ventoy-06280737 版本

你上次传给我的文件：
`openwrt-buddha-v6[2021]-x86-64-generic-squashfs-combined.img.gz   md5:ed4634d0945d65f63e4a5c302c8a1705`
解压后得到：
`openwrt-buddha-v6[2021]-x86-64-generic-squashfs-combined.img   md5:636a4585de017ea5a8ce5d8dde2809fd`


我用上面这个Ventoy版本重新在U盘上安装，只拷贝 `openwrt-buddha-v6[2021]-x86-64-generic-squashfs-combined.img` 进去，不放 ventoy-openwrt.xz文件，直接启动，**没有这个提示**。

你看看哪一步有问题？

**Comment by ventoy** [comment]
上述 img 文件通过 7z 打开，可以看到有 dm-mod.ko 文件，就不会有提示。

![image](https://user-images.githubusercontent.com/59477474/124858517-c8d4f500-dfe0-11eb-9f07-516f6e3fec35.png)

**Comment by esirplayground** [comment]
> 
> 
> 上述 img 文件通过 7z 打开，可以看到有 dm-mod.ko 文件，就不会有提示。
> 
> ![image](https://user-images.githubusercontent.com/59477474/124858517-c8d4f500-dfe0-11eb-9f07-516f6e3fec35.png)

抱歉，是我的失误，我测试用的不是发给你的版本，而是小幅更新过的。请忽略之前的错误反馈。

以`ventoy-06280737`为例，测试情况如下：
| 固件类型 | 取得方式|内核有无kmod-dm|有无ventoy dm插件 |启动情况 |
| :-----| :----: |:----: | :----: | :----: |
| 官方1907-squash/ext4 版本 |官网下载|N | N |失败|
| 官方1907-squash/ext4 版本 |官网下载|N | Y |成功|
| 官方SNAPSHOT-squash/ext4 版本 |自编译| Y | N |失败|
| 官方SNAPSHOT-squash/ext4 版本 |自编译| Y | Y |成功|
| Lean-squash/ext4 版本 |自编译|Y | N |失败|
| Lean-squash/ext4 版本 |自编译|Y | Y |成功|
  
**发现：**
1. 未备ventoy_openwrt.xz，启动均`失败`，无论内核是否有`kmod-dm`，下载自官方网站的1907还会有“无法找到插件”的报错<br>
2. 已备ventoy_openwrt.xz，启动均`成功`，无论内核是否有`kmod-dm`，无论固件下载自官网还是编译<br>
  
**总结：**
备有ventoy-dm插件可以大幅提高ventoy对openwrt固件兼容性，提高启动成功率<br>
  
**建议：**
由于openwrt的代码变化剧烈，内核及磁盘引导部分改动非常频繁，即使内核编译了kmod-dm仍然有可能不能顺利启动。
为了能更好的适应未来代码变化，我能接受`无论内核是否包含kmod-dm组件，都必须在hd0分区ventoy目录备存ventoy-dm插件`的做法
以上建议仅供参考。感觉大佬可以发个新版了，呵呵。

**Comment by ventoy** [comment]
官方网站下载的img文件，里面没有dm模块，所以如果此时没有插件就会提示。
你自己编译的版本你确认里面包含里的  dm-mod.ko 和 dax.ko 吗？像上面图片那样能看到这两个ko文件吗？
你这里自编译的启动失败，意思是，不放插件文件，确实也不会再提示了，但是最终启动失败，是这样吗？

你自编译的img文件也给我共享一个看一下。

**Comment by esirplayground** [comment]
> 
> 
> 官方网站下载的img文件，里面没有dm模块，所以如果此时没有插件就会提示。
> 你自己编译的版本你确认里面包含里的 dm-mod.ko 和 dax.ko 吗？像上面图片那样能看到这两个ko文件吗？
> 你这里自编译的启动失败，意思是，不放插件文件，确实也不会再提示了，但是最终启动失败，是这样吗？
> 
> 你自编译的img文件也给我共享一个看一下。

对的，就是你理解的那样，没有DM插件就不能正常启动。

You have got one transfer，Click link: https://cowtransfer.com/s/c61a2c87bb4846 or use code:552339 to receive your file on cowtransfer.com

openwrt-buddha-v6[2021]-x86-64-generic-squashfs-combined.7z
---
MD5: 31D7D67A0F9C2B1565443FECD4C4A938
SHA1: 9E5B7621D89797E90D3970DFD7A1AE28A5DB86EF
CRC32: 30A3927A

openwrt-x86-64-SNAPSHOT-generic-squashfs-combined.7z
---
MD5: 35D60584AC3E81DC52AD27F125ACB85F
SHA1: E243FB78F5FC4393BFF95BA900FBBCC36965C413
CRC32: 2E9624C2

**Comment by ventoy** [comment]
之前的版本有个BUG，才会导致即使img里面有了dm-mod还是不能正常启动。我已经修复了。你可以使用下面这个CI版本测试一下。
https://github.com/ventoy/Ventoy/actions/runs/1014710726


正常就应该是如果img里面有dm-mod了，就不用放插件了，此时不会有提示，也能够正常启动。
如果img里面没有dm-mod，则必须放插件才可以启动。
因为插件里面也就是放了个dm-mod模块，img里有了就不用重复放了。

**Comment by esirplayground** [comment]
> 
> 
> 之前的版本有个BUG，才会导致即使img里面有了dm-mod还是不能正常启动。我已经修复了。你可以使用下面这个CI版本测试一下。
> https://github.com/ventoy/Ventoy/actions/runs/1014710726
> 
> 正常就应该是如果img里面有dm-mod了，就不用放插件了，此时不会有提示，也能够正常启动。
> 如果img里面没有dm-mod，则必须放插件才可以启动。
> 因为插件里面也就是放了个dm-mod模块，img里有了就不用重复放了。

还发现个Bug，在Ventoy启动引导后，先选择了内核没有kmod-dm的固件（如官方1907），在报告没有ventoy插件后按Enter回到主菜单，再次选择其他内核有kmod-dm固件时，会继续报找不到插件的错误；必须重启再次引导后，直接选择内核有kmod-dm的固件，可以正常引导进入。

**Comment by ventoy** [comment]
已经修复，请使用下面版本测试：
https://github.com/ventoy/Ventoy/actions/runs/1016962957

**Comment by esirplayground** [comment]
> 
> 
> 已经修复，请使用下面版本测试：
> https://github.com/ventoy/Ventoy/actions/runs/1016962957

测试通过
